Krypto - Metrics webapp
Moses-chibuike/Krypto pull request #4
Opened 2023-04-19 16:47 UTC by Moses-chibuike

- Built the project as a single-page application (SPA) with React and Redux.
- Stored the data retrieved from the API in the Redux store.
- Deployed the web app on render and added the live link to the READme file
- Filtered the data that was retrieved from the API using a Filter stateless component.
- Made every page (the main page and the pages for each item) have a unique route within the SPA.
- Recorded a 4mins+ video describing the project and added the video link to the READme file

2023-04-19 18:14 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Moses-chibuike👋, 

### You are doing a marvelous job on the React capstone project and this is one of the best projects I have seen so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://user-images.githubusercontent.com/83803414/233156373-8f437eaa-7531-43f0-9f51-523f7d50962d.png)

## To Highlight 🎉
- All tests are passed. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 18:14 UTC, thecodechaser commented on src/Pages/Home.js
> +            key={exchange.id}
- [ ] Please make sure every page (the main page and the pages for each item) should have a unique route as requested in the project requirements. Currently, All crypto's pages are showing on the same route`(/details`, For a unique route you can use the names of cryptos and pass them in the URL to use in the route. You can read more about React dynamic routing [here](https://dev.to/shubhamtiwari909/dynamic-routes-in-react-491g)

![image](https://user-images.githubusercontent.com/83803414/225131891-6660557e-5184-435e-8410-7aba3b72c4ae.png)

![image](https://user-images.githubusercontent.com/83803414/233155281-1c136933-556c-4c79-9b57-23e26db30a85.png)

![image](https://user-images.githubusercontent.com/83803414/233155364-9d83027b-23a0-4afd-abe6-e4b9a225c5c7.png)

2023-04-19 18:14 UTC, thecodechaser commented on README.md
> +
- [ ] Please make sure in the presentation video also to show some piece of code that you're proud of as requested in the project requirements. (You need to record the presentation video again).

2023-04-19 18:14 UTC, thecodechaser commented on README.md
> +  - [🛠 Built With](#built-with)
- [ ] Please make sure the project is deployed online and add the live demo link to the README file as requested in the project requirements.

![image](https://user-images.githubusercontent.com/83803414/233157826-28873905-cc4d-45a2-80b8-9be13fa80ca8.png)

2023-04-19 18:14 UTC, thecodechaser commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] Please make sure to give appropriate credit to the author in the README for the original design idea as requested in the project requirements.

![image](https://user-images.githubusercontent.com/83803414/233157726-5501c72b-ecee-4234-bf92-f7414a4d2775.png)

2023-04-20 11:49 UTC, MahmoudBakr23 approved these changes
Hi @Moses-chibuike 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done on making the required changes and well done on this great project overall 💯 

Cheers, and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 22:52 UTC, merged